-- require("core.plugin_config.gruvbox")
require("core.plugin_config.github_theme")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.lspconfig")
require("core.plugin_config.mason-lspconfig")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.toggleterm")
require("core.plugin_config.bufferline")
require("core.plugin_config.rust-vim")
require("core.plugin_config.inlay-hints")
